export const USERS_ACTION_TYPE = { 
	USERS_DATA_GET_PENDING: 'USERS_ACTION_TYPE.USERS_DATA_GET_PENDING',
	USERS_DATA_GET_SUCCESS: 'USERS_ACTION_TYPE.USERS_DATA_GET_SUCCESS',
	USERS_DATA_GET_ERROR: 'USERS_ACTION_TYPE.USERS_DATA_GET_ERROR',
	}
